name: Update App Data

on:
  schedule:
    - cron: '0 */4 * * *'  # Her 4 saatte bir
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp
          
      - name: Run app tracker
        run: |
          python main.py
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: false
          
      - name: Create Release
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          name: App Data Update ${{ github.run_number }}
          tag_name: update-${{ github.run_number }}
          body_path: docs/data/index.json